#PBS -N test_mpi
#PBS -l nodes=1:ppn=10 -q debug
#PBS -l walltime=00:02:00
#PBS -j oe
#PBS -A PHS0336 

# submit with 'qsub [name of the script]'
# find out start time with 'showstart [job id]'
# find stats of the queue with 'qstat -u medirz90'
# delete job with 'qdel [job id]'
# or with 'qstop [job id]'  
# see the balance with 'OSCusage'



#--- notes
# aug 27: only main and known
# run with 'qsub -t 1-9 -v iscont=1 eboss_ezmock_512.job'
#---- environment variables and activation
#set -x


#module load cuda/10.1.168

# manually add the path, later we will install the pipeline with `pip`
source ${HOME}/.bashrc

export PYTHONPATH=${HOME}/github/sysnetdev:${HOME}/github/LSSutils:${PYTHONPATH}
export NUMEXPR_MAX_THREADS=2
source activate sysnet

cd ${HOME}/github/LSSutils/scripts/analysis


mpiexec python test_mpi.py
